version: '3.8'

services:
  notification-service:
    container_name: notifications
    image: notifications:1.0.0
    environment:
      - NODE_ENV:${NODE_ENV}
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - nestjs-network
    restart: unless-stopped

networks:
  nestjs-network:
    name: nestjs-network
    external: true
